### PR TITLE
chore(plugins): Keep plugins up to date

### PR DESCRIPTION
**Pull request by gounthar**
We have defined a set of plugins we want to use for this simple example, but it would be nice to keep them updated.
Whenever we want to have the exhaustive list of plugins used in our instance, with the latest versions available, we can use this set of commands:

```
export JENKINS_HOST=localhost:8080
curl -sSL "http://admin:admin@$JENKINS_HOST/pluginManager/api/xml?depth=1&xpath=/*/*/shortName|/*/*/version&wrapper=plugins" | perl -pe 's/.*?<shortName>([\w-]+).*?<version>([^<]+)()(<\/\w+>)+/\1 \2\n/g'|sed 's/ /:/' > /tmp/jenkins_plugins.txt
sort -o /tmp/sorted_jenkins_plugins.txt /tmp/jenkins_plugins.txt
sed -i '1s/^/# See https:\/\/github.com\/jenkinsci\/docker#usage-1\n/' /tmp/sorted_jenkins_plugins.txt
```

Yes, there are more plugins than the ones we installed at first; there are default plugins bundled with Jenkins. 🤷 

We could run this set of commands regularly to get the latest plugins versions, but... we would then get too big a list, with the risk of keeping a plugin that is not mandatory anymore in future versions of Jenkins.
In another project, I have a Jenkinsfile that calls such a script, and that proposes automatic PRs to keep plugins.txt up to date, but I don't feel like it's something that should be bundled with this project.
It's a tool for this set of tutorials, and should not be part of the tutorial itself.

I would definitely prefer to keep a small mandatory list of plugins instead of this long list, but we would then have to use something like updatecli, which is outside the target of this project.

@jmMeessen @berviantoleo : don't feel like you have to merge this PR, it's more of an open discussion.
@ash-sxn : take some time to review and test on your side, please.

### CODE REVIEW

**Comment by berviantoleo** [comment]
I'm curious. Is it sufficient to use this https://github.com/jenkinsci/plugin-installation-manager-tool? I haven't used it before, but I think it could be great to experiment with it.

**Comment by gounthar** [comment]
I've never used it, but it looks promising.
It seems to solve most of the issues I raised here. 👍

**Comment by berviantoleo** [comment]
Example command:

```bash
docker run --rm -v ./plugins.txt:/var/jenkins_home/plugins.txt jenkins/jenkins:2.411-jdk11 jenkins-plugin-cli --plugin-file /var/jenkins_home/plugins.txt --no-download --available-updates
```

My first experiment:

* Have any updates:

first

* No Updates:

no updates

* Multiple updates:
 
multiple

I think this solution will not straight forward, since we will need to convert the list become txt.

**Comment by gounthar** [comment]
`jenkins-plugin-cli --plugin-file /usr/share/jenkins/plugins.txt --no-download --available-updates --output txt` works fine for me.

**Comment by ash-sxn** [comment]
Can you please explain how'll we implement this?

**Comment by gounthar** [comment]
See #45 .

**Pull request closed without merging**
