### PR TITLE
(Bug): Gitpod URL

### LINKED ISSUE #50: Implementation of the GitPod URL seems broken
Ref PR #36 

There seems to be still some friction with the full implementation of the PR : `./gitpodURL.sh: line 13: (...) Permission denied`.

The displayed URL is correct. Running the script with sudo failed to display the correct URL but didn't have the error.

```
gitpod /workspace/GSoC-2023-docker-based-quickstart/experimental_docker_compose_files/02_custom_docker_file_connecting_agent_and_controller (bug/empty_url_issue34) $ ./gitpodURL.sh 
Jenkins can Be accessed here: https://8080-ashsxn-gsoc2023dockerba-npa4vn1sfrh.ws-eu100.gitpod.io
./gitpodURL.sh: line 13: /workspace/GSoC-2023-docker-based-quickstart/experimental_docker_compose_files/02_custom_docker_file_connecting_agent_and_controller/dockerfiles/jenkins.yaml.tmp: Permission denied
```

### PR DESCRIPTION
**Pull request by ash-sxn**
- resolves #50
- I was not able to find the reason why it is happening but putting all the commands in a single `init:` with `&&` solved the problem
- Pinging  mentors @berviantoleo @gounthar @jmMeessen

### CODE REVIEW

**Comment by ash-sxn** [comment]
Yes, so that the new user doesn't have to do anything different when using gitpod.
Isn't it mandatory to run it before `docker compose up`, since it edits the `jenkins.yaml` file?

**Comment by gounthar** [comment]
It is mandatory, but isn't GitPod running it by itself before the workspace is available for the user?

**Review by gounthar — CHANGES_REQUESTED** [review]
Shouldn't you put all that in a bash script and then call it instead of this long line?

**Comment by ash-sxn** [comment]
So, right now 
should we merge this, since it works? then revisit the issue after the 1st milestone.

**Review by jmMeessen — APPROVED** [review]
LGTM
(although we need to revisit this later)

**Review by gounthar — APPROVED** [review]

**Pull request merged**
