### PR TITLE
Real jobs

### LINKED ISSUE #126: Get the GitHub action to test the real job
We're only testing the simple first job that does not do much.
We should test for each sample a real job that is linked to the tutorial (maven for maven, node for node, and so on).

### PR DESCRIPTION
**Pull request by ash-sxn**
- it test the real jobs by adding the xml file to the dockerfile 
- fixes #126 
- still getting the build to fail(`BUILD_STATUS=FAILURE`), working on this rightnow

### CODE REVIEW

**Comment by gounthar** [comment]
I can see [build failures](https://github.com/ash-sxn/GSoC-2023-docker-based-quickstart/actions/runs/5747675098/job/15579105158), right?

**Comment by gounthar** [comment]
I can't see the full job console text, but it looks like [it worked](https://github.com/ash-sxn/GSoC-2023-docker-based-quickstart/actions/runs/5765760805), right?

**Comment by ash-sxn** [comment]
Yes!, 
I've made it so that console can be seen when the job fails. you can see it in the node part(it's still failing)
but it still shows success with a green tick on the node part too for which I am thinking to fail when the build fails

**Comment by gounthar** [comment]
Ok, thanks a lot for the clarification.
We're near the end on this one, good job! 🚀

**Comment by ash-sxn** [comment]
This PR is working now.
Should we merge this?

**Review by gounthar — APPROVED** [review]

**Pull request merged**
